{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "rlqs.fullname" . }}
  labels:
    {{- include "rlqs.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "rlqs.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: {{ .Values.service.grpcPort }}
          protocol: TCP
        - port: {{ .Values.service.metricsPort }}
          protocol: TCP
      {{- with .Values.networkPolicy.ingress.from }}
      from:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
