apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "rlqs.fullname" . }}
  labels:
    {{- include "rlqs.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "rlqs.selectorLabels" . | nindent 6 }}
