services:
  rlqs-server:
    build:
      context: ../..
      dockerfile: Dockerfile
    command: ["-config", "/etc/rlqs/config.yaml"]
    ports:
      - "18081:18081"
    volumes:
      - ./rlqs-config.yaml:/etc/rlqs/config.yaml:ro

  envoy:
    image: envoyproxy/envoy:v1.32-latest
    ports:
      - "10000:10000"   # HTTP listener
      - "9901:9901"     # Envoy admin
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
    depends_on:
      - rlqs-server
